application: scott1028001
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /public
  static_dir: public
  
- url: .*
  script: scott1028001.app

libraries:
- name: webapp2
  version: "2.5.2"
